name: elderly_squire_capstone
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1



environment:
    sdk: ">=2.7.0 <3.0.0"
#    sdk: '>=2.8.0-dev.0 <2.8.0'
#    sdk: ">=2.12.0 <3.0.0"
#    sdk: ">=2.14.0 <3.0.0"


analyzer:
  enable-experiment:
    - non-nullable


dependencies:
  flutter:
    sdk: flutter
  form_field_validator: ^1.0.1
  flare_flutter: '^1.7.4'
  url_launcher: ^4.0.3
  intro_slider: ^2.3.4
  cached_network_image: ^2.1.0
  flutter_cache_manager: ^1.2.0
  webview_flutter: ^0.3.1
  http: ^0.12.0
  cloud_functions: ^0.9.0
  cupertino_list_tile: ^0.2.0
  splashscreen:



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_core: "0.7.0"
  firebase_auth: "^0.20.1"
  cloud_firestore: "^0.16.0"
  flutter_slidable: ^0.5.7
  provider: ^4.3.2+2
#  rxdart: ^0.22.0------original
  rxdart: ^0.23.1
  shared_preferences: 0.5.2
  flutter_local_notifications: ^1.4.4+2
  grouped_list: ^4.2.0
  intl: ^0.16.1





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo/Mediminder_Logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

  - assets/images/elderly_squire_logo.png
  - assets/images/elderly_squire_logo2.png
  - assets/images/elderly_squire_logo_classic.png
  - assets/images/elderly_squire_logo_classic_icon.png
  - assets/images/lola.png
  - assets/images/lolo.png
  - assets/images/nursing.jpg
  - assets/images/volunteer.jpg
  - assets/images/medicine.jpg
  - assets/images/retirement.jpg
  - assets/images/healthy_elders.jpg
  - assets/images/reminder.png
  - assets/images/todolist.png
  - assets/images/GSIS_logo.png
  - assets/images/PagIbig_logo.png
  - assets/images/Philhealth_logo.png
  - assets/images/SSS_logo.png
  - assets/images/weight-scale.png
  - assets/images/exercise_new.png
  - assets/images/tape_measure.png
  - assets/images/fruits_veggie.png
  - assets/images/diet.png
  - assets/images/diet2.png
  - assets/images/weights_new.png
  - assets/images/dumbbell.png
  - assets/images/bike.png
  - assets/images/meal.png
  - assets/images/therapy.png
  - assets/images/chat-box.png
  - assets/images/chat.png
  - assets/animations/
  - assets/sound/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: OpenSans
        fonts:
          - asset:  assets/fonts/OpenSans-Light.ttf

      - family: Montserrat
        fonts:
          - asset:  assets/fonts/Montserrat-Light.ttf

      - family: ShadowsIntoLight
        fonts:
          - asset:  assets/fonts/ShadowsIntoLight-Regular.ttf

      - family: BebasNeue
        fonts:
          - asset:  assets/fonts/BebasNeue-Regular.ttf

      - family: Anton
        fonts:
          - asset:  assets/fonts/Anton-Regular.ttf

      - family: Pacifico
        fonts:
          - asset:  assets/fonts/Pacifico-Regular.ttf

      - family: RobotoSlab
        fonts:
          - asset:  assets/fonts/RobotoSlab-Light.ttf

      - family: PTSans
        fonts:
          - asset:  assets/fonts/PTSans-Regular.ttf

      - family: Ic
        fonts:
          - asset: assets/fonts/ic/ic_medicine.ttf

      - family: Angel
        fonts:
          - asset: assets/fonts/neu/Angel Signature.ttf
  #  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
